name: rick_and_morty_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  theme:
    path: lib/packages/theme
  repository:
    path: lib/packages/repository
  api:
    path: lib/packages/api
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  go_router: ^14.8.1
  go_router_builder: ^2.8.2
  cached_network_image: ^3.4.1
  bloc_concurrency: ^0.3.0

  path_provider: ^2.1.5
  freezed_annotation: ^3.0.0
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4

flutter:

  uses-material-design: true
