name: api
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: ^8.1.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  chopper_generator: ^8.1.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4


flutter:

